.TH librfid-send_script 1 "January 24, 2008"
.SH NAME
librfid-send_script \- Command line tool for testing librfid
.SH SYNOPSIS
.BR librfid-send_script " scriptfile"
.SH DESCRIPTION
.B librfid-send_script
is a command line tool for testing librfid.
.SH OPTIONS
None.
.SH BUGS
Please report any bugs on the
.B librfid-devel
mailing list at
.BR https://lists.gnumonks.org/mailman/listinfo/librfid-devel/ "."
.SH LICENCE
.B librfid-send_script
is covered by the GNU General Public License (GPL), version 2.
.SH AUTHORS
Harald Welte <laforge@gnumonks.org>
.PP
This manual page was written by Uwe Hermann <uwe@hermann-uwe.de>.
It is licensed under the terms of the GNU GPL (version 2 or later).
